#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use Symfony\Component\Console\Application;
$app = new Application();
$app -> add(new AdventOfCode\TwentyTwentyThree\Day01Command());
$app -> add(new AdventOfCode\TwentyTwentyThree\Day02Command());
$app -> run();